# Generated by Django 5.1.4 on 2025-03-09 04:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Base", "0004_alter_message_options_alter_room_options_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(default="avatars/avatar.png", upload_to="avatars/"),
        ),
    ]
