# Generated by Django 5.1.4 on 2025-03-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Base", "0005_alter_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(default="images/avatar.png", upload_to="avatars/"),
        ),
    ]
